@id = 2da43bfd-00b2-4577-81cf-dc588ed0d07c

PUT http://localhost:5051/breakfasts/{{id}}
Content-Type: application/json

{
  "name": "ASdasdas",
  "description": "Vegan everything! Join us for a healthy breakfast..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": ["Oatmeal", "Avocado Toast", "Omelette", "Salad"],
  "Sweet": ["Cookie"]
}

